In [ ]:
# download data from compas

from geoband.API import *

GetCompasData('PJT001_TripChain.csv')
GetCompasData('PJT001_stations_table.csv')
GetCompasData('PJT001_moc_link_2018.geojson')
GetCompasData('PJT001_h_100m_cell_flow.geojson')
GetCompasData('PJT001_h_100m_cell_pop.geojson')
GetCompasData('PJT001_sk_emd_od.csv')
GetCompasData('PJT001_tl_scco_emd.geojson')
GetCompasData('PJT001_routestationinfo.csv')

In [1]:
import pandas as pd
import geopandas as gpd

# read in data

tripChain = pd.read_csv('PJT001_TripChain.csv')
stations = pd.read_csv('PJT001_stations_table.csv')
mocLink = gpd.read_file('PJT001_moc_link_2018.geojson')
cellFlow = gpd.read_file('PJT001_h_100m_cell_flow.geojson')
cellPop = gpd.read_file('PJT001_h_100m_cell_pop.geojson')
emdOd = pd.read_csv('PJT001_sk_emd_od.csv')
emd = gpd.read_file('PJT001_tl_scco_emd.geojson')
routeStationInfo = pd.read_csv('PJT001_routestationinfo.csv')

In [2]:
tripChain.columns

Index(['암호화카드번호||'', ''||트랜잭션ID||'', ''||환승횟수||'', ''||교통카드발행사ID||'',
       ''||총이용객수||'', ''||사용자구분||'', ''||교통수단CD1||'', ''||교통수단CD2||'',
       ''||교통수단CD3||'', ''||교통수단CD4||'', ''||교통수단CD5||'', ''||버스노선ID1||'',
       ''||버스노선ID2||'', ''||버스노선ID3||'', ''||버스노선ID4||'', ''||버스노선ID5||'',
       ''||차량ID1||'', ''||차량ID2||'', ''||차량ID3||'', ''||차량ID4||'',
       ''||차량ID5||'', ''||총통행거리||'', ''||총탑승시간||'', ''||총소요시간||'',
       ''||승차일시1||'', ''||승차일시2||'', ''||승차일시3||'', ''||승차일시4||'',
       ''||승차일시5||'', ''||하차일시1||'', ''||하차일시2||'', ''||하차일시3||'',
       ''||하차일시4||'', ''||하차일시5||'', ''||최초승차일시||'', ''||최종하차일시||'',
       ''||승차역ID1||'', ''||승차역ID2||'', ''||승차역ID3||'', ''||승차역ID4||'',
       ''||승차역ID5||'', ''||하차역ID1||'', ''||하차역ID2||'', ''||하차역ID3||'',
       ''||하차역ID4||'', ''||하차역ID5||'', ''||최초승차역ID||'', ''||최종하차역ID||'',
       ''||총이용금액||'', ''||수집건수||'', ''||트립체인완료코드'],
      dtype='object')

In [3]:
# 컬럼이름을 좀 이쁘게 만들어 보자

tripChain.columns=['암호화카드번호', '트랜잭션ID', '환승횟수', '교통카드발행사ID',
       '총이용객수', '사용자구분', '교통수단CD1', '교통수단CD2',
       '교통수단CD3', '교통수단CD4', '교통수단CD5', '버스노선ID1',
       '버스노선ID2', '버스노선ID3', '버스노선ID4', '버스노선ID5',
       '차량ID1', '차량ID2', '차량ID3', '차량ID4',
       '차량ID5', '총통행거리', '총탑승시간', '총소요시간',
       '승차일시1', '승차일시2', '승차일시3', '승차일시4',
       '승차일시5', '하차일시1', '하차일시2', '하차일시3',
       '하차일시4', '하차일시5', '최초승차일시', '최종하차일시',
       '승차역ID1', '승차역ID2', '승차역ID3', '승차역ID4',
       '승차역ID5', '하차역ID1', '하차역ID2', '하차역ID3',
       '하차역ID4', '하차역ID5', '최초승차역ID', '최종하차역ID',
       '총이용금액', '수집건수', '트립체인완료코드']

In [4]:
tripChain.isnull().sum()

암호화카드번호            0
트랜잭션ID             0
환승횟수               0
교통카드발행사ID          0
총이용객수              0
사용자구분              0
교통수단CD1           34
교통수단CD2       613273
교통수단CD3       950179
교통수단CD4      1032934
교통수단CD5      1045309
버스노선ID1        65601
버스노선ID2       711144
버스노선ID3       958733
버스노선ID4      1034162
버스노선ID5      1045668
차량ID1             34
차량ID2         613273
차량ID3         950179
차량ID4        1032934
차량ID5        1045309
총통행거리              0
총탑승시간              0
총소요시간              0
승차일시1             34
승차일시2         613273
승차일시3         950179
승차일시4        1032934
승차일시5        1045309
하차일시1          12118
하차일시2         615926
하차일시3         950797
하차일시4        1033038
하차일시5        1045322
최초승차일시             0
최종하차일시             0
승차역ID1            34
승차역ID2        613273
승차역ID3        950179
승차역ID4       1048575
승차역ID5       1048575
하차역ID1       1048575
하차역ID2       1048575
하차역ID3       1048575
하차역ID4       1033038
하차역ID5       1045322
최초승차역ID      1048575
최종하차역ID        15176
총이용금액              0
수집건수               0
트립체인완료코드           0
dtype: int64

In [5]:
stations.표준정류장ID.unique().size

37832

In [6]:
stations.shape

(38509, 12)

In [7]:
stations.head(100)

,표준정류장ID,시군명,정류소명,정류소영문명,정류소번호,중앙차로여부,관할관청,위치,WGS84위도,WGS84경도,모바일정류장ID,이비카드정류장ID
0,228003422,용인시,손골마을회관.국제학교,"Songol Community Center,",56443.0,노변정류장,경기도 용인시,NaN,37.342517,127.066817,56443.0,NaN
1,228003423,용인시,풀잎사랑,Pulipsarang,56444.0,노변정류장,경기도 용인시,NaN,37.341800,127.068983,56444.0,NaN
2,228003424,용인시,풀잎사랑,Pulipsarang,56445.0,노변정류장,경기도 용인시,NaN,37.341817,127.069083,56445.0,NaN
3,228003425,용인시,대성공정,Daesung Process,56446.0,노변정류장,경기도 용인시,NaN,37.339350,127.073067,56446.0,NaN
4,228003426,용인시,대성공정,Daesung Process,56447.0,노변정류장,경기도 용인시,NaN,37.339183,127.073400,56447.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95,116000581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[None None None None None None None None None ...,4113713.0
96,116000582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[None None None None None None None None None ...,4114378.0
97,116000583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[None None None None None None None None None ...,4114379.0
98,116000609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[None None None None None None None None None ...,4197289.0
99,116000609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[None None None None None None None None None ...,9197289.0

In [8]:
stations.drop_duplicates(subset ="표준정류장ID", keep = 'first', inplace = True)

In [9]:
stations.shape

(37832, 12)

In [10]:
routeStationInfo.shape

(37831, 7)

In [11]:
# 화성시 버스노선만 뽑아내자

station_office = pd.DataFrame(stations['표준정류장ID'])
station_office['시군명'] = stations['시군명']
station_office.isnull().sum()
station_office

         표준정류장ID  시군명
0      228003422  용인시
1      228003423  용인시
2      228003424  용인시
3      228003425  용인시
4      228003426  용인시
...          ...  ...
38504  228003381  용인시
38505  228003382  용인시
38506  236001229  포천시
38507  236001230  포천시
38508  236001234  포천시

[37832 rows x 2 columns]

In [12]:
station_office.표준정류장ID.unique().size

37832

In [13]:
route_station = pd.merge(routeStationInfo, station_office[['표준정류장ID', '시군명']], how = 'left', left_on = 'station_id', right_on='표준정류장ID')
route_station

,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
0,65286,228000018,10-4,1,용인터미널,228001552,47634.0,228001552,용인시
1,65287,228000018,10-4,2,용인터미널(경유),277102443,NaN,277102443,용인시
2,65288,228000018,10-4,3,포브스병원,228000443,29439.0,228000443,용인시
3,65289,228000018,10-4,4,제일교회,228000665,29881.0,228000665,용인시
4,65290,228000018,10-4,5,라이프아파트,228000664,29457.0,228000664,용인시
...,...,...,...,...,...,...,...,...,...
37826,191750,241491011,38-1,63,신일해피트리후문,233002733,NaN,233002733,화성시
37827,191751,241491011,38-1,64,기배동행정복지센터,233002726,NaN,233002726,화성시
37828,191752,241491011,38-1,65,기안1통입구,233002959,NaN,233002959,화성시
37829,191753,241491011,38-1,66,배양2리,233002717,55455.0,233002717,화성시
37830,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시

In [14]:
# 시군명이 null 값인 정류장이 2535개나 된다..

route_station[route_station['시군명'].isna()]

,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
120,65498,228000020,7,23,영문2리,228002092,47343.0,228002092,NaN
240,65747,228000055,22,46,에이스카운티,228001803,56703.0,228001803,NaN
322,66259,228000113,9-1,22,영문2리,228002092,47343.0,228002092,NaN
413,66579,228000136,2,39,영문2리,228002092,47343.0,228002092,NaN
520,66727,228000148,3,63,드라마사거리,230001301,51090.0,230001301,NaN
...,...,...,...,...,...,...,...,...,...
37674,191598,241491008,38,50,신한미지엔정문,233001284,55697.0,233001284,NaN
37753,191677,241491010,100,8,파크자이1차,233003172,55583.0,233003172,NaN
37754,191678,241491010,100,9,파크자이2차,233003170,55581.0,233003170,NaN
37756,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,NaN
37762,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,NaN

In [15]:
station_null = pd.merge(stations, routeStationInfo[['station_id', 'station_nm']], how='inner', left_on='표준정류장ID', right_on = 'station_id')
station_null = station_null.drop('정류소명', 1)
station_null = station_null.rename(columns={'station_nm': '정류소명'})
station_null.to_csv('station_null.csv', sep=',')

In [16]:
# stations2 = 시군명 결측치를 수동으로 채운 station 테이블
stations2 = pd.read_csv('./station_null2.csv')
stations2 = stations2.drop('station_id', 1)
stations2

,Unnamed: 0,표준정류장ID,시군명,정류소명,정류소영문명,정류소번호,중앙차로여부,관할관청,위치,WGS84위도,WGS84경도,모바일정류장ID,이비카드정류장ID
0,0,228003422,용인시,손골마을회관.국제학교,"Songol Community Center,",56443.0,노변정류장,경기도 용인시,NaN,37.342517,127.066817,56443,NaN
1,1,228003423,용인시,풀잎사랑,Pulipsarang,56444.0,노변정류장,경기도 용인시,NaN,37.341800,127.068983,56444,NaN
2,2,228003424,용인시,풀잎사랑,Pulipsarang,56445.0,노변정류장,경기도 용인시,NaN,37.341817,127.069083,56445,NaN
3,3,228003425,용인시,대성공정,Daesung Process,56446.0,노변정류장,경기도 용인시,NaN,37.339350,127.073067,56446,NaN
4,4,228003426,용인시,대성공정,Daesung Process,56447.0,노변정류장,경기도 용인시,NaN,37.339183,127.073400,56447,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39452,39452,236001229,포천시,평강식물원,Pyunggang Botanical Garden,40691.0,노변정류장,경기도 포천시,경기도 포천시 영북면,38.050650,127.306617,40691,NaN
39453,39453,236001230,포천시,양문1리.영중면사무소,"Yangmun 1-ri, Yeongjung-myeon Office",40699.0,노변정류장,경기도 포천시,NaN,38.005517,127.245667,40699,NaN
39454,39454,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN
39455,39455,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN
39456,39456,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN

In [17]:
# 다시한번 화성시 버스노선만 뽑아내자

station_office2 = pd.DataFrame(stations2['표준정류장ID'])
station_office2['시군명'] = stations2['시군명']
station_office2.isnull().sum()
station_office2.drop_duplicates(subset ="표준정류장ID", keep = 'first', inplace = True) 
station_office2

         표준정류장ID  시군명
0      228003422  용인시
1      228003423  용인시
2      228003424  용인시
3      228003425  용인시
4      228003426  용인시
...          ...  ...
39449  228003381  용인시
39450  228003382  용인시
39451  236001229  포천시
39453  236001230  포천시
39454  236001234  포천시

[16326 rows x 2 columns]

In [18]:
route_station2 = pd.merge(routeStationInfo, station_office2, how = 'inner', left_on = 'station_id', right_on='표준정류장ID')
route_station2

,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
0,65286,228000018,10-4,1,용인터미널,228001552,47634.0,228001552,용인시
1,65476,228000020,7,1,용인터미널,228001552,47634.0,228001552,용인시
2,65528,228000021,8,1,용인터미널,228001552,47634.0,228001552,용인시
3,65702,228000055,22,1,용인터미널,228001552,47634.0,228001552,용인시
4,66238,228000113,9-1,1,용인터미널,228001552,47634.0,228001552,용인시
...,...,...,...,...,...,...,...,...,...
37826,191612,241491008,38,64,배양1동,233532650,NaN,233532650,화성시
37827,191688,241491011,38-1,1,배양1동,233532650,NaN,233532650,화성시
37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시
37829,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,화성시
37830,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,화성시

In [19]:
stations2[stations2["시군명"] == "화성시"].count()

Unnamed: 0    11243
표준정류장ID       11243
시군명           11243
정류소명          11243
정류소영문명        10340
정류소번호          9592
중앙차로여부        10273
관할관청          10340
위치             7920
WGS84위도       10825
WGS84경도       10825
모바일정류장ID      10133
이비카드정류장ID      7901
dtype: int64

In [20]:
# 시군명이 null인애들을 다시한번 수동으로 채워볼게요 (앞뒤 정류장의 시군명이랑 비교해서!)

sgname_null = pd.DataFrame(route_station2[route_station2['시군명'].isnull()]['pr_station_id'])
sgname_null.drop_duplicates(subset ="pr_station_id", keep = 'first', inplace = True) 
sgname_null

       pr_station_id
3959       229000030
6561       232000006
6574       232000073
6955       232000028
13419      233000125
13420      233000139
13421      233000140
13422      233000258
13423      233000269
14570      233000131
14571      233000135
14572      233000136
14573      233000142
14574      233000265
14575      233000270
14576      234000314
17076      234000007
17928      234000034
17929      234000072
17930      234000082
18187      234000035
25018      239000124
25533      240000015
28780      241216001
30836      241317010
33257      241382001
35148      241420005
35953      241427002
37145      241461007
37323      241483012
37417      241483020

In [21]:
pd.set_option('display.max_rows', 500)

In [22]:
route_station2[route_station2['pr_station_id'] == 241483020]

# 시군명이 null값인 애들을 일일히 다 확인해봤으나 화성시 내부만 돌아다니는 버스노선은 없었음 ! => null값인 애들들도 다 drop하고 진행할게요

,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
8008,189106,241483020,22-3(장전),19,천천리입구,233000712,37316.0,233000712,화성시
8015,189107,241483020,22-3(장전),20,삼미.쌍용아파트,233000711,37324.0,233000711,화성시
8021,189108,241483020,22-3(장전),21,오목천동태산아파트.서희스타힐스,201000025,2059.0,201000025,수원시
8030,189109,241483020,22-3(장전),22,수원여자대학교입구,201000024,2070.0,201000024,수원시
8039,189110,241483020,22-3(장전),23,서수원주민편익시설,201000365,2872.0,201000365,수원시
8051,189111,241483020,22-3(장전),24,고색초교.태산아파트,201000023,2124.0,201000023,수원시
8063,189112,241483020,22-3(장전),25,신병원.대원.거산아파트,201000022,2131.0,201000022,수원시
8076,189113,241483020,22-3(장전),26,공구유통타운.중앙자동차매매단지,201000336,2832.0,201000336,수원시
8089,189114,241483020,22-3(장전),27,동남아파트,201000432,2934.0,201000432,수원시
8113,189116,241483020,22-3(장전),29,동남아파트,201000431,2933.0,201000431,수원시
8123,189117,241483020,22-3(장전),30,공구유통타운.중앙자동차매매단지,201000020,2156.0,201000020,수원시
8135,189118,241483020,22-3(장전),31,고색파출소.종합공구단지,201000064,2137.0,201000064,수원시
8147,189119,241483020,22-3(장전),32,신병원.대원.거산아파트,201000019,2128.0,201000019,수원시
8162,189120,241483020,22-3(장전),33,고색초교.태산아파트,201000018,2122.0,201000018,수원시
8173,189121,241483020,22-3(장전),34,서수원주민편익시설,201000488,2972.0,201000488,수원시
8179,189122,241483020,22-3(장전),35,수원여자대학입구,201000017,2067.0,201000017,수원시
8186,189123,241483020,22-3(장전),36,오목천동태산아파트.서희스타힐스,201000016,2058.0,201000016,수원시
8193,189124,241483020,22-3(장전),37,삼미.쌍용아파트,233000782,37325.0,233000782,화성시
8201,189125,241483020,22-3(장전),38,천천리입구,233000781,37321.0,233000781,화성시
8704,189089,241483020,22-3(장전),2,삼화리,233000724,37162.0,233000724,화성시
8711,189090,241483020,22-3(장전),3,천산아파트,233000723,37169.0,233000723,화성시
8718,189091,241483020,22-3(장전),4,비봉초등학교후문,233000722,37171.0,233000722,화성시
8726,189092,241483020,22-3(장전),5,비봉중고등학교,233000721,37186.0,233000721,화성시
8731,189093,241483020,22-3(장전),6,연화가든앞,233002039,55017.0,233002039,화성시
8732,189137,241483020,22-3(장전),50,연화가든앞,233002039,55017.0,233002039,화성시
8947,189094,241483020,22-3(장전),7,왕재골입구,233002040,55008.0,233002040,화성시
8948,189138,241483020,22-3(장전),51,왕재골입구,233002040,55008.0,233002040,화성시
8954,189139,241483020,22-3(장전),52,비봉중고등학교,233000778,37183.0,233000778,화성시
8962,189140,241483020,22-3(장전),53,비봉초등학교후문.삼화3리,233000777,37170.0,233000777,화성시
8970,189141,241483020,22-3(장전),54,천산아파트,233000776,37168.0,233000776,화성시
8978,189142,241483020,22-3(장전),55,삼화리.천산아파트,233000774,37161.0,233000774,화성시
11935,189095,241483020,22-3(장전),8,구포리과수원,233000720,37200.0,233000720,화성시
11940,189096,241483020,22-3(장전),9,쌍학리,233000719,37620.0,233000719,화성시
11945,189097,241483020,22-3(장전),10,숙곡리천불사,233000718,37237.0,233000718,화성시
11950,189098,241483020,22-3(장전),11,어천,233000842,37565.0,233000842,화성시
11957,189100,241483020,22-3(장전),13,51사단,233000717,37290.0,233000717,화성시
11964,189101,241483020,22-3(장전),14,원평,233000716,37295.0,233000716,화성시
11970,189103,241483020,22-3(장전),16,전승아파트,233000715,37304.0,233000715,화성시
11976,189104,241483020,22-3(장전),17,옥산마을,233000714,37308.0,233000714,화성시
11982,189105,241483020,22-3(장전),18,천천리,233000713,37312.0,233000713,화성시
12581,189126,241483020,22-3(장전),39,천천리,233000849,37313.0,233000849,화성시
12587,189127,241483020,22-3(장전),40,옥산마을,233000848,37309.0,233000848,화성시
12593,189128,241483020,22-3(장전),41,전승아파트,233000847,37305.0,233000847,화성시
12600,189130,241483020,22-3(장전),43,원평,233000846,37299.0,233000846,화성시
12607,189131,241483020,22-3(장전),44,51사단,233000845,37291.0,233000845,화성시
12612,189133,241483020,22-3(장전),46,어천,233000844,37566.0,233000844,화성시
12617,189134,241483020,22-3(장전),47,숙곡리천불사,233000843,37238.0,233000843,화성시
12622,189135,241483020,22-3(장전),48,구포3리,233000780,37612.0,233000780,화성시
13107,189115,241483020,22-3(장전),28,수원역.역전시장,202000225,3023.0,202000225,수원시
13362,189099,241483020,22-3(장전),12,어천저수지,233002149,55106.0,233002149,화성시
13367,189102,241483020,22-3(장전),15,매송초등학교,233000891,37298.0,233000891,화성시
13493,189129,241483020,22-3(장전),42,매송초등학교,233002174,55188.0,233002174,화성시
13499,189132,241483020,22-3(장전),45,어천저수지,233002150,55107.0,233002150,화성시
37417,189088,241483020,22-3(장전),1,장전출발(경유),277101941,NaN,277101941,NaN
37418,189136,241483020,22-3(장전),49,비봉교차로,233002321,55226.0,233002321,화성시
37420,189143,241483020,22-3(장전),56,장전도착(경유),277101809,NaN,277101809,NaN

In [23]:
route_station2.sort_values(by=['pr_station_id', 'bus_line_no_seq'])

,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
0,65286,228000018,10-4,1,용인터미널,228001552,47634.0,228001552,용인시
16,65287,228000018,10-4,2,용인터미널(경유),277102443,NaN,277102443,용인시
25,65288,228000018,10-4,3,포브스병원,228000443,29439.0,228000443,용인시
30,65289,228000018,10-4,4,제일교회,228000665,29881.0,228000665,용인시
33,65290,228000018,10-4,5,라이프아파트,228000664,29457.0,228000664,용인시
...,...,...,...,...,...,...,...,...,...
27281,191750,241491011,38-1,63,신일해피트리후문,233002733,NaN,233002733,화성시
27144,191751,241491011,38-1,64,기배동행정복지센터,233002726,NaN,233002726,화성시
37750,191752,241491011,38-1,65,기안1통입구,233002959,NaN,233002959,화성시
27147,191753,241491011,38-1,66,배양2리,233002717,55455.0,233002717,화성시
37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시

In [24]:
# 우리는 661개의 unique 한 버스노선 데이터를 가지고 있지요!

route_station2.pr_station_id.unique().size

661

In [25]:
buses_not_hwaseong = []

for index, row in route_station2.iterrows():
    if(row['시군명'] != '화성시'):
        buses_not_hwaseong.append(row['pr_station_id'])

In [26]:
# 이중에 화성시 밖을 다니는 버스들은 buses_not_hwaseong 이라는 리스트에 저장해 둘게요!

buses_not_hwaseong = list(dict.fromkeys(buses_not_hwaseong))

In [27]:
# 화성시 밖을 나가는 버스노선은 총 493개
# 화성시 안만을 다니는 버스는 총 661-493 = 168개 네요?

len(buses_not_hwaseong)

493

### hwaseong_buses 라는 dataframe에 화성시 안만을 다니는 버스노선의 데이터를 저장해놓을게요!

route_station_hwaseong = route_station2
route_station_hwaseong

for index, row in route_station_hwaseong.iterrows():
    if row['pr_station_id'] in buses_not_hwaseong:
        route_station_hwaseong.drop(index, inplace = True)
        
route_station_hwaseong.to_csv('route_station_hwaseong.csv', sep=',')

In [28]:
# 노선 168개만 남은걸 보니 잘 drop했나보군요!

route_station_hwaseong = pd.read_csv('./route_station_hwaseong.csv')
route_station_hwaseong.pr_station_id.unique().size

168

In [29]:
route_station_hwaseong

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
0,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시
1,1465,164078,241317009,39,2,장지동,233000167,36809.0,233000167,화성시
2,1469,164084,241317009,39,8,롯데캐슬.제일풍경채,233003130,55526.0,233003130,화성시
3,1473,164085,241317009,39,9,자이파밀리에,233003131,55527.0,233003131,화성시
4,1562,164113,241317009,39,37,자이파밀리에,233003163,55560.0,233003163,화성시
...,...,...,...,...,...,...,...,...,...,...
7810,37826,191612,241491008,38,64,배양1동,233532650,NaN,233532650,화성시
7811,37827,191688,241491011,38-1,1,배양1동,233532650,NaN,233532650,화성시
7812,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시
7813,37829,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,화성시
7814,37830,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,화성시

In [30]:
route_station_hwaseong[route_station_hwaseong['pr_station_id'] == 233000096]

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
589,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시
1319,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시
1342,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시
1353,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시
1365,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시
1374,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시
1382,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시
1390,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시
1398,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시
1476,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시
1485,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시
1494,10114,91288,233000096,27,15,장안우체국,233002512,55389.0,233002512,화성시
1506,10128,91289,233000096,27,16,사곡6리,233000487,37431.0,233000487,화성시
1519,10143,91290,233000096,27,17,장안여자중학교,233000486,36917.0,233000486,화성시
1530,10155,91282,233000096,27,9,화산삼거리,233001554,36701.0,233001554,화성시
1533,10159,91283,233000096,27,10,기아2차아파트앞,233002268,55143.0,233002268,화성시
1536,10163,91284,233000096,27,11,석천1리포도원,233000473,36906.0,233000473,화성시
1539,10167,91285,233000096,27,12,두레자연중고등학교,233001383,36951.0,233001383,화성시

In [31]:
route_station_hwaseong[route_station_hwaseong['bus_line_no'] == '7-1'].sort_values('bus_line_no_seq')

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
1310,9899,90000,233000056,7-1,1,조암터미널,233000929,36011.0,233000929,화성시
5268,27110,153426,241205003,7-1,1,수원과학대학,233000913,36212.0,233000913,화성시
5273,27118,153427,241205003,7-1,2,대한적십자교육원,233002492,55447.0,233002492,화성시
1578,10221,90001,233000056,7-1,2,조암리(경유),277102394,NaN,277102394,화성시
5277,27125,153428,241205003,7-1,3,남산공단입구,233000610,36249.0,233000610,화성시
2332,11082,90002,233000056,7-1,3,어은삼거리,233000402,37594.0,233000402,화성시
5314,27212,153429,241205003,7-1,4,흥법사입구,233000574,36217.0,233000574,화성시
2336,11088,90003,233000056,7-1,4,거문들,233002134,55160.0,233002134,화성시
5316,27215,153430,241205003,7-1,5,수기리아랫말,233000573,36197.0,233000573,화성시
2339,11091,90004,233000056,7-1,5,어은1정미소앞,233000401,36869.0,233000401,화성시
5318,27218,153431,241205003,7-1,6,호수마을,233002955,NaN,233002955,화성시
2342,11095,90005,233000056,7-1,6,어은1리,233000400,37453.0,233000400,화성시
2345,11099,90006,233000056,7-1,7,어은1리한양빌라앞,233001775,37800.0,233001775,화성시
5320,27221,153432,241205003,7-1,7,보통리입구,233000914,36158.0,233000914,화성시
2347,11101,90007,233000056,7-1,8,금의1리입구,233000398,36870.0,233000398,화성시
5322,27224,153433,241205003,7-1,8,수원신학교,233000572,36751.0,233000572,화성시
2350,11105,90008,233000056,7-1,9,수촌3리,233000397,37454.0,233000397,화성시
5324,27227,153434,241205003,7-1,9,분천리,233002551,36139.0,233002551,화성시
2353,11110,90009,233000056,7-1,10,수촌3리,233000396,36871.0,233000396,화성시
5325,27229,153435,241205003,7-1,10,협성대,233002557,36129.0,233002557,화성시
2355,11113,90010,233000056,7-1,11,수촌1리,233000395,36872.0,233000395,화성시
5326,27231,153436,241205003,7-1,11,한신아파트,233000917,36125.0,233000917,화성시
3532,13042,153437,241205003,7-1,12,봉담읍행정복지센터,233000786,36122.0,233000786,화성시
654,9102,90011,233000056,7-1,12,성문,233000394,37166.0,233000394,화성시
657,9106,90012,233000056,7-1,13,해창2리.능인대학원대학교,233000393,37179.0,233000393,화성시
4572,15449,153438,241205003,7-1,13,국민체육센터,233002217,55139.0,233002217,화성시
665,9117,90013,233000056,7-1,14,해창1리.우리꽃식물원,233001402,37206.0,233001402,화성시
4575,15454,153439,241205003,7-1,14,봉담중.고등학교,233001661,37883.0,233001661,화성시
675,9129,90014,233000056,7-1,15,매곡리,233000391,37217.0,233000391,화성시
4579,15460,153440,241205003,7-1,15,동일하이빌.상봉초등학교,233002086,55054.0,233002086,화성시
5327,27232,153441,241205003,7-1,16,하나로마트.화성고용센터,233001756,37756.0,233001756,화성시
2357,11116,90015,233000056,7-1,16,고주리입구.한국폴리텍대학,233001550,36695.0,233001550,화성시
2359,11118,90016,233000056,7-1,17,제암리입구,233001570,37623.0,233001570,화성시
5328,27237,153442,241205003,7-1,17,동화휴먼시아2단지,233002016,55001.0,233002016,화성시
2362,11121,90017,233000056,7-1,18,고주리마을회관,233001508,37426.0,233001508,화성시
5329,27243,153443,241205003,7-1,18,동화휴먼시아3.4단지.봉담우체국,233001757,37773.0,233001757,화성시
2364,11123,90018,233000056,7-1,19,고주리,233001510,36736.0,233001510,화성시
4595,15488,153444,241205003,7-1,19,주공5단지,233002041,55040.0,233002041,화성시
5330,27249,153445,241205003,7-1,20,효행초등학교정문,233002245,55244.0,233002245,화성시
2366,11125,90019,233000056,7-1,20,고주리.동방산업단지,233001571,37624.0,233001571,화성시
2369,11128,90020,233000056,7-1,21,발안주공아파트,233001935,37941.0,233001935,화성시
5333,27253,153446,241205003,7-1,21,봉담푸르지오.아이파크,233002743,55443.0,233002743,화성시
5336,27257,153447,241205003,7-1,22,쌍용아파트,233002742,NaN,233002742,화성시
2373,11132,90021,233000056,7-1,22,발안마을주공아파트,233000523,36908.0,233000523,화성시
2376,11137,90022,233000056,7-1,23,우림아파트.화성노인회관,233000522,37428.0,233000522,화성시
5339,27260,153448,241205003,7-1,23,동부아파트,233002740,NaN,233002740,화성시
2094,10812,90023,233000056,7-1,24,화성시보건소앞,233000388,36875.0,233000388,화성시
5342,27263,153449,241205003,7-1,24,신명아파트,233002754,NaN,233002754,화성시
2105,10831,90024,233000056,7-1,25,발안만세시장,233000387,36876.0,233000387,화성시
5344,27265,153450,241205003,7-1,25,수원대입구,233003021,NaN,233003021,화성시
3366,12538,153451,241205003,7-1,26,와우2리,233000945,36194.0,233000945,화성시
3370,12545,153452,241205003,7-1,27,와우농협앞,233001457,37529.0,233001457,화성시
5348,27270,153453,241205003,7-1,28,보보스.롯데슈퍼,233002728,NaN,233002728,화성시
5351,27273,153454,241205003,7-1,29,기안중학교,233002729,NaN,233002729,화성시
5354,27276,153455,241205003,7-1,30,기안성당,233002731,NaN,233002731,화성시
5357,27279,153456,241205003,7-1,31,신일해피트리후문,233002733,NaN,233002733,화성시
5286,27142,153457,241205003,7-1,32,기배동행정복지센터,233002726,NaN,233002726,화성시
5360,27282,153458,241205003,7-1,33,신미주아파트후문,233002718,55633.0,233002718,화성시
5361,27284,153459,241205003,7-1,34,신미주아파트남문.예일유치원,233002720,55635.0,233002720,화성시
5362,27286,153460,241205003,7-1,35,신미주아파트,233002722,NaN,233002722,화성시
5363,27287,153461,241205003,7-1,36,신미주아파트남문.예일유치원,233002721,55636.0,233002721,화성시
5364,27289,153462,241205003,7-1,37,신미주아파트후문,233002719,55634.0,233002719,화성시
5293,27177,153463,241205003,7-1,38,기배동행정복지센터,233002725,NaN,233002725,화성시
5365,27291,153464,241205003,7-1,39,신일해피트리후문,233002734,NaN,233002734,화성시
5368,27294,153465,241205003,7-1,40,기안성당,233002732,NaN,233002732,화성시
5371,27297,153466,241205003,7-1,41,기안중학교,233002730,NaN,233002730,화성시
5374,27300,153467,241205003,7-1,42,보보스.롯데슈퍼,233002727,NaN,233002727,화성시
2983,12015,153468,241205003,7-1,43,와우농협앞,233000942,36187.0,233000942,화성시
2987,12022,153469,241205003,7-1,44,와우2리,233000944,36193.0,233000944,화성시
5377,27303,153470,241205003,7-1,45,수원대입구,233003020,NaN,233003020,화성시
5381,27308,153471,241205003,7-1,46,신명아파트,233002753,NaN,233002753,화성시
5383,27310,153472,241205003,7-1,47,동부아파트,233002739,NaN,233002739,화성시
5386,27313,153473,241205003,7-1,48,쌍용아파트,233002741,55440.0,233002741,화성시
5389,27318,153474,241205003,7-1,49,봉담푸르지오.아이파크,233002744,55441.0,233002744,화성시
5392,27322,153475,241205003,7-1,50,임광그대가3단지,233002246,55245.0,233002246,화성시
5395,27326,153476,241205003,7-1,51,주공5단지,233002566,55449.0,233002566,화성시
5398,27332,153477,241205003,7-1,52,동화초.동화휴먼시아3단지,233000951,36728.0,233000951,화성시
5399,27338,153478,241205003,7-1,53,동화휴먼시아2단지,233001615,37679.0,233001615,화성시
5400,27344,153479,241205003,7-1,54,동화마을1단지.화성고용센터,233001616,37680.0,233001616,화성시
4507,15372,153480,241205003,7-1,55,동화휴먼시아1단지.상봉초등학교,233002085,55062.0,233002085,화성시
5132,16578,153481,241205003,7-1,56,동문아파트.협성대학교.봉담중고교,233001617,37681.0,233001617,화성시
5401,27349,153482,241205003,7-1,57,봉담호수공원.신협앞,233002084,55055.0,233002084,화성시
5403,27353,153483,241205003,7-1,58,봉담한신아파트,233000570,36124.0,233000570,화성시
5405,27357,153484,241205003,7-1,59,협성대학교,233002552,36130.0,233002552,화성시
5406,27360,153485,241205003,7-1,60,분천교회.분천리,233002550,36143.0,233002550,화성시
5407,27362,153486,241205003,7-1,61,수원신학교,233000567,36752.0,233000567,화성시
5409,27365,153487,241205003,7-1,62,보통리입구,233000915,36156.0,233000915,화성시
5411,27368,153488,241205003,7-1,63,호수마을,233002755,NaN,233002755,화성시
5413,27371,153489,241205003,7-1,64,아랫말.수기리,233000566,36200.0,233000566,화성시
5415,27374,153490,241205003,7-1,65,수기리,233000565,36214.0,233000565,화성시
5301,27191,153491,241205003,7-1,66,남산공단입구,233000607,36246.0,233000607,화성시
5306,27199,153492,241205003,7-1,67,편의점,233002535,55448.0,233002535,화성시
5311,27207,153493,241205003,7-1,68,수원과학대학,233000912,36213.0,233000912,화성시

In [32]:
route_station_hwaseong.isna().sum()

Unnamed: 0           0
seq                  0
pr_station_id        0
bus_line_no          0
bus_line_no_seq      0
station_nm           0
station_id           0
mobile_no          877
표준정류장ID              0
시군명                  0
dtype: int64

In [33]:
# 화성 내부만 다니는 버스 노선들은 hwaseong_buses에 저장해 놓을게요

hwaseong_buses = route_station_hwaseong.pr_station_id.unique()
hwaseong_buses

array([241317009, 241483001, 241319005, 241319006, 241319007, 241319033,
       241319032, 241319029, 241483002, 241319002, 241319003, 241319004,
       241319008, 241319012, 241319013, 241319020, 241319021, 241319022,
       241319023, 241319024, 241319025, 241319026, 241319027, 241319028,
       241319031, 241319034, 241319036, 241319037, 241319039, 241319041,
       241319042, 241483008, 241319009, 241319010, 241319011, 241319015,
       241319016, 241319018, 241319019, 241319030, 241319043, 241319044,
       241335001, 241335026, 241483007, 241483016, 241335002, 241483009,
       233000134, 241205012, 241483004, 241483005, 241483006, 241483010,
       241483014, 241483017, 241485040, 241319035, 233000010, 233000013,
       233000015, 233000019, 233000021, 233000022, 233000024, 233000025,
       233000026, 233000027, 233000029, 233000030, 233000035, 233000041,
       233000044, 233000046, 233000047, 233000048, 233000049, 233000051,
       233000052, 233000057, 233000060, 233000062, 233000079, 233000080,
       233000081, 233000085, 233000094, 233000095, 233000096, 233000126,
       233000267, 233000056, 233000040, 233000043, 233000045, 233000058,
       233000059, 241485041, 241485039, 233000264, 241205014, 241205015,
       241483018, 241483019, 241485006, 241485015, 241485016, 241485017,
       241485018, 241485019, 241485020, 241485021, 241485022, 241485038,
       241485042, 241485048, 241485049, 241485050, 241485051, 241485052,
       241485054, 241485024, 241485045, 241485046, 241485047, 241485055,
       241205016, 241205017, 241205018, 241485053, 233000064, 241485035,
       233000028, 233000034, 241205003, 241491008, 241491011, 241491004,
       241491009, 241491002, 241491003, 241491005, 241205013, 233000275,
       241318002, 233000128, 241205023, 241317002, 241317004, 241317008,
       241491010, 241324001, 241324005, 241324004, 241205022, 233000268,
       233000281, 241317007, 241205008, 241483022, 233000141, 233000252,
       233000130, 241317011, 241323001, 241324002, 241324003, 241483003])

In [34]:
# 화성시 내부만 다니는 버스 노선들이 지나는 모든 정류장을 hwaseong_station에 저장할게요

hwaseong_stations = route_station_hwaseong.표준정류장ID.unique()
hwaseong_stations

array([233000168, 233000167, 233003130, ..., 233532650, 233002346,
       233002005])

# 버스노선별로 tripchain테이블에서의 이용횟수를 구할게요

tripChain2 = tripChain

tripChain2['버스노선ID1'] = tripChain2['버스노선ID1'].fillna(0)
tripChain2['버스노선ID2'] = tripChain2['버스노선ID2'].fillna(0)
tripChain2['버스노선ID3'] = tripChain2['버스노선ID3'].fillna(0)
tripChain2['버스노선ID4'] = tripChain2['버스노선ID4'].fillna(0)
tripChain2['버스노선ID5'] = tripChain2['버스노선ID5'].fillna(0)


bus_user_num = {}

for index, row in tripChain2.iterrows():
    if row['버스노선ID1'] in bus_user_num:
        bus_user_num[row['버스노선ID1']] = bus_user_num[row['버스노선ID1']] + 1
    else:
        bus_user_num[row['버스노선ID1']] = 1
    
    if row['버스노선ID2'] in bus_user_num:
        bus_user_num[row['버스노선ID2']] = bus_user_num[row['버스노선ID2']] + 1
    else:
        bus_user_num[row['버스노선ID2']] = 1
    
    if row['버스노선ID3'] in bus_user_num:
        bus_user_num[row['버스노선ID3']] = bus_user_num[row['버스노선ID3']] + 1
    else:
        bus_user_num[row['버스노선ID3']] = 1
    
    if row['버스노선ID4'] in bus_user_num:
        bus_user_num[row['버스노선ID4']] = bus_user_num[row['버스노선ID4']] + 1
    else:
        bus_user_num[row['버스노선ID4']] = 1
    
    if row['버스노선ID5'] in bus_user_num:
        bus_user_num[row['버스노선ID5']] = bus_user_num[row['버스노선ID5']] + 1
    else:
        bus_user_num[row['버스노선ID5']] = 1
        
most_bus_route = pd.DataFrame.from_dict(bus_user_num, orient='index')
most_bus_route.columns = ['이용횟수']
most_bus_route = most_bus_route.drop(0.0)
most_bus_route

most_bus_route.to_csv('bus_route_usage_count.csv', sep=',')

In [35]:
most_bus_route = pd.read_csv('./bus_route_usage_count.csv')

In [36]:
most_bus_route.sort_values(by ='이용횟수',  ascending=False).head(100)

     Unnamed: 0   이용횟수
23   41002046.0  78759
2    41031040.0  61357
0    41002045.0  53846
17   41027009.0  49515
14   41031020.0  46958
20   41031024.0  43246
1    41002044.0  40389
11   41027004.0  38067
9    41036102.0  33222
64   41036108.0  30401
31   41031108.0  29797
24   41036110.0  28564
45   41067012.0  27895
12   41036111.0  27797
5    41020001.0  25767
72   41074077.0  25529
26   41031046.0  24886
28   41008170.0  22084
42   41036113.0  21198
22   41031004.0  20336
35   41008148.0  19998
3    41031121.0  19402
30   41027008.0  18451
4    41031013.0  18416
87   41002090.0  18361
46   41036132.0  18250
76   41036131.0  16341
44   41002038.0  16291
55   41031030.0  15060
16   41067005.0  13166
125  41067131.0  12234
33   41031110.0  12179
43   41031125.0  11919
85   41031109.0  11793
101  41008152.0  11584
29   41086002.0  10967
27   41036115.0  10584
6    41067109.0  10165
117  41003338.0   9769
61   41067135.0   9011
57   41036006.0   8218
77   41074061.0   7530
10   41031065.0   7495
39   41031019.0   6646
78   41086011.0   6595
102  41036105.0   6566
79   41003103.0   6291
36   41031002.0   6184
185  41086008.0   5504
32   41031009.0   5490
18   41061025.0   5375
73   41031107.0   4941
75   41036128.0   4817
141  41031140.0   4498
69   41036012.0   4461
92   41031016.0   4149
54   41031132.0   4139
114  41031048.0   4066
67   41031001.0   4006
132  41324002.0   3891
91   41006241.0   3746
119  41075031.0   3652
25   41031141.0   3552
244  41036103.0   3465
145  41036116.0   3452
138  41086005.0   3452
107  41008006.0   3374
124  41008151.0   3362
148  41075017.0   3310
126  41031018.0   3297
298  41027001.0   3054
225  41006255.0   3017
152  41007133.0   2976
127  41036039.0   2931
130  41031042.0   2912
217  41201005.0   2859
194  41031118.0   2840
200  41036032.0   2725
110  41008007.0   2719
62   41027010.0   2715
83   41074080.0   2568
146  41006407.0   2553
99   41012101.0   2546
89   41074072.0   2488
204  41061027.0   2451
198  41006239.0   2405
51   41002902.0   2317
13   41324001.0   2246
58   41036123.0   2156
131  41323002.0   2156
160  41002632.0   2149
90   41003900.0   2108
95   41323005.0   2083
189  41317002.0   2001
128  41036026.0   1961
255  41003683.0   1907
21   41075011.0   1895
154  41031052.0   1860
80   41036040.0   1852
306  41488002.0   1842

In [37]:
# 이비노선ID와 포준노선ID 매핑 테이블이 제공되었네요!

from geoband.API import *

GetCompasData('PJT001_routestationmapping.csv')
route_station_mapping = pd.read_csv('PJT001_routestationmapping.csv')
route_station_mapping

        구분     운수사명    운수사ID     이비노선ID    표준노선ID    노선명
0     경기시내    경원여객M  2805000  216000044  28050900  M6410
1     경기시내     강화운수  4100100  232000028  41001001      2
2     경기시내     강화운수  4100100  232000029  41001013     88
3     경기시내     강화운수  4100100  232000061  41001020   3000
4     경기시내     강화운수  4100100  232000067  41001024    388
...    ...      ...      ...        ...       ...    ...
2122  경기시내     서현운수  4108800  229000060  41088004    330
2123  경기시내     서현운수  4108800  229000063  41088005    850
2124  경기시내  코레일네트웍스  4108900  213000024  41089001   8507
2125  경기시내     신성교통  4109100  229000102  41091900  M7111
2126  경기시내     군포여객  4109400  225000004  41094001    100

[2127 rows x 6 columns]

In [38]:
# route_station_hwaseong_with_eb 테이블은 route_station_hwaseong + 표준노선ID

route_station_hwaseong_with_eb = pd.merge(route_station_hwaseong, route_station_mapping[['표준노선ID', '이비노선ID']], how = 'left', left_on = 'pr_station_id', right_on='이비노선ID')
route_station_hwaseong_with_eb

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명,표준노선ID,이비노선ID
0,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시,NaN,NaN
1,1465,164078,241317009,39,2,장지동,233000167,36809.0,233000167,화성시,NaN,NaN
2,1469,164084,241317009,39,8,롯데캐슬.제일풍경채,233003130,55526.0,233003130,화성시,NaN,NaN
3,1473,164085,241317009,39,9,자이파밀리에,233003131,55527.0,233003131,화성시,NaN,NaN
4,1562,164113,241317009,39,37,자이파밀리에,233003163,55560.0,233003163,화성시,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7810,37826,191612,241491008,38,64,배양1동,233532650,NaN,233532650,화성시,NaN,NaN
7811,37827,191688,241491011,38-1,1,배양1동,233532650,NaN,233532650,화성시,NaN,NaN
7812,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시,NaN,NaN
7813,37829,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,화성시,NaN,NaN
7814,37830,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,화성시,NaN,NaN

In [42]:
route_station_hwaseong_with_eb[route_station_hwaseong_with_eb['pr_station_id'] == 233000096]

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명,표준노선ID,이비노선ID
589,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,41008157.0,233000096.0
1319,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,41008157.0,233000096.0
1342,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,41008157.0,233000096.0
1353,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,41008157.0,233000096.0
1365,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,41008157.0,233000096.0
1374,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,41008157.0,233000096.0
1382,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,41008157.0,233000096.0
1390,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,41008157.0,233000096.0
1398,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,41008157.0,233000096.0
1476,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,41008157.0,233000096.0
1485,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,41008157.0,233000096.0
1494,10114,91288,233000096,27,15,장안우체국,233002512,55389.0,233002512,화성시,41008157.0,233000096.0
1506,10128,91289,233000096,27,16,사곡6리,233000487,37431.0,233000487,화성시,41008157.0,233000096.0
1519,10143,91290,233000096,27,17,장안여자중학교,233000486,36917.0,233000486,화성시,41008157.0,233000096.0
1530,10155,91282,233000096,27,9,화산삼거리,233001554,36701.0,233001554,화성시,41008157.0,233000096.0
1533,10159,91283,233000096,27,10,기아2차아파트앞,233002268,55143.0,233002268,화성시,41008157.0,233000096.0
1536,10163,91284,233000096,27,11,석천1리포도원,233000473,36906.0,233000473,화성시,41008157.0,233000096.0
1539,10167,91285,233000096,27,12,두레자연중고등학교,233001383,36951.0,233001383,화성시,41008157.0,233000096.0

In [40]:
route_station_hwaseong_with_eb.isna().sum()

Unnamed: 0            0
seq                   0
pr_station_id         0
bus_line_no           0
bus_line_no_seq       0
station_nm            0
station_id            0
mobile_no           877
표준정류장ID               0
시군명                   0
표준노선ID             5799
이비노선ID             5799
dtype: int64

In [41]:
# 화성시 내부만 다니는 버스는 총 168개인데..
route_station_hwaseong_with_eb.pr_station_id.unique().size

168

In [43]:
# 우리가 알수있는 화성시 내부순환버스의 이용량은 최대 48개밖에 안되요..
route_station_hwaseong_with_eb.표준노선ID.unique().size

48

In [44]:
hwaseong_buses_eb = route_station_hwaseong_with_eb.표준노선ID.unique()
hwaseong_buses_eb

array([      nan, 41061022., 41008001., 41008101., 41008103., 41008110.,
       41008112., 41008115., 41008114., 41008105., 41008117., 41008108.,
       41008107., 41008106., 41008119., 41008125., 41008127., 41008129.,
       41008130., 41008131., 41008132., 41008133., 41008134., 41008139.,
       41008142., 41008144., 41008145., 41008146., 41008147., 41008150.,
       41008155., 41008156., 41008157., 41008161., 41008138., 41008124.,
       41008126., 41008128., 41008140., 41008141., 41075035., 41008137.,
       41008102., 41008118., 41075031., 41086009., 41075030., 41075017.])

In [45]:
route_station_hwaseong_with_eb.isna().sum()

Unnamed: 0            0
seq                   0
pr_station_id         0
bus_line_no           0
bus_line_no_seq       0
station_nm            0
station_id            0
mobile_no           877
표준정류장ID               0
시군명                   0
표준노선ID             5799
이비노선ID             5799
dtype: int64

In [46]:
most_bus_route

      Unnamed: 0   이용횟수
0     41002045.0  53846
1     41002044.0  40389
2     41031040.0  61357
3     41031121.0  19402
4     41031013.0  18416
...          ...    ...
2214  41011104.0      1
2215  41003583.0      1
2216  41304006.0      1
2217  41002164.0      1
2218  41002207.0      1

[2219 rows x 2 columns]

In [47]:
most_bus_route_hwaseong = most_bus_route
most_bus_route_hwaseong = most_bus_route_hwaseong.rename(columns={'Unnamed: 0' : 'pr_station_id' })
most_bus_route_hwaseong

      pr_station_id   이용횟수
0        41002045.0  53846
1        41002044.0  40389
2        41031040.0  61357
3        41031121.0  19402
4        41031013.0  18416
...             ...    ...
2214     41011104.0      1
2215     41003583.0      1
2216     41304006.0      1
2217     41002164.0      1
2218     41002207.0      1

[2219 rows x 2 columns]

In [48]:
for index, row in most_bus_route_hwaseong.iterrows():
    if (row['pr_station_id'] not in hwaseong_buses_eb):
        most_bus_route_hwaseong.drop(index, inplace = True)
        
        
#화성시 내부만 다니는 버스 이용량 순위
most_bus_route_hwaseong.sort_values(by='이용횟수', ascending = False)

      pr_station_id  이용횟수
119      41075031.0  3652
148      41075017.0  3310
82       41061022.0  1130
170      41086009.0   978
47       41075030.0   867
231      41008001.0   228
601      41008124.0    24
605      41008141.0    21
467      41008125.0    20
1827     41008137.0    18
1751     41075035.0    14
1267     41008146.0    12
540      41008140.0    10
1171     41008156.0     8
732      41008144.0     8
1285     41008103.0     8
599      41008161.0     8
2079     41008117.0     6
1703     41008102.0     5
1250     41008131.0     5
1541     41008101.0     5
787      41008128.0     4
1659     41008126.0     4
1258     41008133.0     4
1379     41008110.0     3
2078     41008105.0     3
1741     41008115.0     2
1878     41008119.0     2
2113     41008142.0     2
1413     41008112.0     1
2162     41008145.0     1
2177     41008134.0     1
2192     41008118.0     1

In [49]:
# 이용량많은 버스노선 시각화
top_hwaseong_buses_route = most_bus_route_hwaseong.sort_values(by='이용횟수', ascending = False).head(10)
top_hwaseong_buses_route

      pr_station_id  이용횟수
119      41075031.0  3652
148      41075017.0  3310
82       41061022.0  1130
170      41086009.0   978
47       41075030.0   867
231      41008001.0   228
601      41008124.0    24
605      41008141.0    21
467      41008125.0    20
1827     41008137.0    18

In [50]:
route_station_mapping[route_station_mapping['노선명'] == '708']

        구분  운수사명    운수사ID     이비노선ID    표준노선ID  노선명
2014  경기시내  화성운수  4107500  223000056  41067131  708

In [51]:
top_hwaseong_buses_route = pd.merge(top_hwaseong_buses_route, route_station_mapping[['이비노선ID', '표준노선ID', '노선명']],how='left', left_on='pr_station_id', right_on = '표준노선ID')
top_hwaseong_buses_route = top_hwaseong_buses_route.drop(['표준노선ID'], axis =1)
top_hwaseong_buses_route

   pr_station_id  이용횟수     이비노선ID   노선명
0     41075031.0  3652  233000128   712
1     41075017.0  3310  233000130  73-1
2     41061022.0  1130  233000134  1001
3     41086009.0   978  233000141   201
4     41075030.0   867  233000252   710
5     41008001.0   228  233000010  33-1
6     41008124.0    24  233000040     6
7     41008141.0    21  233000059  11-5
8     41008125.0    20  233000041    11
9     41008137.0    18  233000064    10

In [52]:
top_hwaseong_buses_station_id = top_hwaseong_buses_route.이비노선ID.unique()
top_hwaseong_buses_station_id

array([233000128, 233000130, 233000134, 233000141, 233000252, 233000010,
       233000040, 233000059, 233000041, 233000064])

In [53]:
route_station_hwaseong

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명
0,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시
1,1465,164078,241317009,39,2,장지동,233000167,36809.0,233000167,화성시
2,1469,164084,241317009,39,8,롯데캐슬.제일풍경채,233003130,55526.0,233003130,화성시
3,1473,164085,241317009,39,9,자이파밀리에,233003131,55527.0,233003131,화성시
4,1562,164113,241317009,39,37,자이파밀리에,233003163,55560.0,233003163,화성시
...,...,...,...,...,...,...,...,...,...,...
7810,37826,191612,241491008,38,64,배양1동,233532650,NaN,233532650,화성시
7811,37827,191688,241491011,38-1,1,배양1동,233532650,NaN,233532650,화성시
7812,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시
7813,37829,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,화성시
7814,37830,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,화성시

In [54]:
stations2

,Unnamed: 0,표준정류장ID,시군명,정류소명,정류소영문명,정류소번호,중앙차로여부,관할관청,위치,WGS84위도,WGS84경도,모바일정류장ID,이비카드정류장ID
0,0,228003422,용인시,손골마을회관.국제학교,"Songol Community Center,",56443.0,노변정류장,경기도 용인시,NaN,37.342517,127.066817,56443,NaN
1,1,228003423,용인시,풀잎사랑,Pulipsarang,56444.0,노변정류장,경기도 용인시,NaN,37.341800,127.068983,56444,NaN
2,2,228003424,용인시,풀잎사랑,Pulipsarang,56445.0,노변정류장,경기도 용인시,NaN,37.341817,127.069083,56445,NaN
3,3,228003425,용인시,대성공정,Daesung Process,56446.0,노변정류장,경기도 용인시,NaN,37.339350,127.073067,56446,NaN
4,4,228003426,용인시,대성공정,Daesung Process,56447.0,노변정류장,경기도 용인시,NaN,37.339183,127.073400,56447,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39452,39452,236001229,포천시,평강식물원,Pyunggang Botanical Garden,40691.0,노변정류장,경기도 포천시,경기도 포천시 영북면,38.050650,127.306617,40691,NaN
39453,39453,236001230,포천시,양문1리.영중면사무소,"Yangmun 1-ri, Yeongjung-myeon Office",40699.0,노변정류장,경기도 포천시,NaN,38.005517,127.245667,40699,NaN
39454,39454,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN
39455,39455,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN
39456,39456,236001234,포천시,포천농협.하나로마트,"Pocheon Nonghyup, Hanaro Mart",40692.0,노변정류장,경기도 포천시,NaN,37.901217,127.206933,40692,NaN

In [55]:
RouteStationInfo_latlon = pd.merge(route_station_hwaseong, stations2[['WGS84위도', 'WGS84경도', '표준정류장ID']], how='left', left_on='표준정류장ID', right_on='표준정류장ID')
RouteStationInfo_latlon

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명,WGS84위도,WGS84경도
0,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시,37.155117,127.117900
1,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시,37.155117,127.117900
2,1462,164077,241317009,39,1,장지동,233000168,36808.0,233000168,화성시,37.155117,127.117900
3,1465,164078,241317009,39,2,장지동,233000167,36809.0,233000167,화성시,37.155867,127.115017
4,1465,164078,241317009,39,2,장지동,233000167,36809.0,233000167,화성시,37.155867,127.115017
...,...,...,...,...,...,...,...,...,...,...,...,...
79297,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시,37.226783,126.997700
79298,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시,37.226783,126.997700
79299,37828,191754,241491011,38-1,67,배양1동,233532650,NaN,233532650,화성시,37.226783,126.997700
79300,37829,191680,241491010,100,11,신창2차비바패밀리,233002346,NaN,233002346,화성시,NaN,NaN
79301,37830,191686,241491010,100,17,원룸단지앞,233002005,37986.0,233002005,화성시,NaN,NaN

In [56]:
RouteStationInfo_latlon[RouteStationInfo_latlon['pr_station_id'] == 233000096]

,Unnamed: 0,seq,pr_station_id,bus_line_no,bus_line_no_seq,station_nm,station_id,mobile_no,표준정류장ID,시군명,WGS84위도,WGS84경도
12225,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12226,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12227,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12228,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12229,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12230,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12231,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12232,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12233,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12234,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12235,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12236,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12237,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12238,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12239,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12240,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12241,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12242,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12243,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12244,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12245,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12246,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12247,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12248,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12249,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12250,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12251,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12252,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12253,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12254,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12255,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12256,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12257,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12258,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12259,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12260,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12261,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12262,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12263,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12264,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12265,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12266,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12267,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12268,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12269,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12270,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12271,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12272,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12273,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12274,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12275,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12276,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12277,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12278,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12279,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12280,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12281,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12282,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12283,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12284,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12285,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12286,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12287,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12288,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12289,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12290,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12291,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12292,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12293,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12294,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12295,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
12296,9035,91291,233000096,27,18,조암터미널,233000928,36013.0,233000928,화성시,37.082233,126.815800
23794,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23795,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23796,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23797,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23798,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23799,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23800,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23801,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23802,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23803,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23804,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23805,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23806,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23807,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23808,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23809,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23810,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23811,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23812,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23813,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23814,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23815,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23816,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23817,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23818,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23819,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23820,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23821,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23822,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23823,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23824,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23825,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23826,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23827,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23828,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23829,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23830,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
23831,9908,91274,233000096,27,1,조암터미널,233000929,36011.0,233000929,화성시,37.082150,126.815583
24364,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24365,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24366,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24367,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24368,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24369,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24370,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24371,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24372,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24373,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24374,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24375,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24376,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24377,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24378,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24379,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24380,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24381,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24382,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24383,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24384,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24385,9933,91275,233000096,27,2,조암삼거리(경유),277102392,NaN,277102392,화성시,37.080933,126.814550
24526,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24527,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24528,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24529,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24530,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24531,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24532,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24533,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24534,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24535,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24536,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24537,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24538,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24539,9946,91276,233000096,27,3,장안여자중학교,233000992,36797.0,233000992,화성시,37.078567,126.815217
24694,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24695,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24696,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24697,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24698,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24699,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24700,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24701,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24702,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24703,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24704,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24705,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24706,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24707,9960,91277,233000096,27,4,사곡6리,233000496,36910.0,233000496,화성시,37.074817,126.815150
24792,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24793,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24794,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24795,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24796,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24797,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24798,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24799,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24800,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24801,9971,91278,233000096,27,5,장안우체국,233002511,55388.0,233002511,화성시,37.072167,126.813850
24872,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24873,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24874,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24875,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24876,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24877,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24878,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24879,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24880,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24881,9981,91279,233000096,27,6,사곡1리,233000993,37478.0,233000993,화성시,37.069083,126.809217
24952,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24953,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24954,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24955,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24956,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24957,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24958,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24959,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24960,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
24961,9991,91280,233000096,27,7,장자터,233001776,37834.0,233001776,화성시,37.066483,126.802167
25032,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25033,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25034,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25035,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25036,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25037,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25038,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25039,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25040,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25041,10001,91281,233000096,27,8,기아생활관,233000485,36918.0,233000485,화성시,37.064383,126.795617
25498,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25499,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25500,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25501,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25502,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25503,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25504,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25505,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25506,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25507,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25508,10092,91286,233000096,27,13,장자터,233001780,37839.0,233001780,화성시,37.066417,126.802250
25597,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250
25598,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250
25599,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250
25600,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250
25601,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250
25602,10103,91287,233000096,27,14,사곡1리,233000476,37434.0,233000476,화성시,37.068900,126.809250

In [ ]:
RouteStationInfo_latlon[RouteStationInfo_latlon['WGS84위도'].isna()]

In [ ]:
# 위도경도 결측치 채우기

hwaseong_bus1 = pd.read_csv('./hwaseong_bus1.csv', encoding = 'euc-kr')
hwaseong_bus2 = pd.read_csv('./hwaseong_bus2.csv', encoding = 'euc-kr')

In [ ]:
hwaseong_bus = pd.concat([hwaseong_bus1, hwaseong_bus2])
hwaseong_bus

In [ ]:
RouteStationInfo_latlon = pd.merge(RouteStationInfo_latlon, hwaseong_bus[['위도', '경도', '정류소명']], how='left', left_on='station_nm', right_on='정류소명')
RouteStationInfo_latlon = RouteStationInfo_latlon.drop(['정류소명'], axis =1)
RouteStationInfo_latlon

In [ ]:
RouteStationInfo_latlon.drop_duplicates(subset ="표준정류장ID", keep = 'first', inplace = True) 
RouteStationInfo_latlon

In [ ]:
RouteStationInfo_latlon['WGS84위도'] = RouteStationInfo_latlon['WGS84위도'].combine_first(RouteStationInfo_latlon['위도'])
RouteStationInfo_latlon['WGS84경도'] = RouteStationInfo_latlon['WGS84경도'].combine_first(RouteStationInfo_latlon['경도'])
RouteStationInfo_latlon = RouteStationInfo_latlon.drop(['위도', '경도'], axis=1)

In [ ]:
RouteStationInfo_latlon

In [ ]:
RouteStationInfo_latlon.to_csv('RouteStationInfo_latlon.csv', sep=',')

In [ ]:
top_hwaseong_buses_station_id

In [ ]:
All_busline = []
bus_num_ = 0
for j in range(len(top_hwaseong_buses_station_id)):
    tmp_busline = RouteStationInfo_latlon[RouteStationInfo_latlon['pr_station_id'] == top_hwaseong_buses_station_id[j]].sort_values(by='bus_line_no_seq')
    tmp_buslineArr = []
    for i in range(len(tmp_busline)):
        tmp = tmp_busline.iloc[i]
        tmp_buslineArr.append((tmp['WGS84위도'], tmp['WGS84경도']))
    All_busline.append(tmp_buslineArr)
    bus_num_ += 1

In [ ]:
All_busline[1]

In [ ]:
import folium

Busline = folium.Map(location = [37.213952,126.9626727], zoom_start=11)

folium.PolyLine(All_busline[0], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[0][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[0][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="red", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[1], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[1][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[1][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="blue", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[2], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[2][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[2][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="green", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[3], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[3][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[3][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="purple", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[4], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[4][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[4][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="orange", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[5], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[5][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[5][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="darkblue", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[6], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[6][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[6][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="darkred", weight=2.5, opacity=1).add_to(Busline)

#folium.PolyLine(All_busline[7], 
#                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[7][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[7][1][1])]['bus_line_no']).iloc[0].iloc[0], 
#                color="pink", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[8], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[8][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[8][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="gray", weight=2.5, opacity=1).add_to(Busline)

folium.PolyLine(All_busline[9], 
                popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[9][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[9][1][1])]['bus_line_no']).iloc[0].iloc[0], 
                color="black", weight=2.5, opacity=1).add_to(Busline)

Busline.save('top_bus_route.html')
Busline

In [ ]:
tripChain.columns

In [ ]:
tripChain3 = tripChain

## 정류장별 이용량 구하기

tripChain3 = tripChain

tripChain3['승차역ID1'] = tripChain3['승차역ID1'].fillna(0)
tripChain3['승차역ID2'] = tripChain3['승차역ID2'].fillna(0)
tripChain3['승차역ID3'] = tripChain3['승차역ID3'].fillna(0)
tripChain3['승차역ID4'] = tripChain3['승차역ID4'].fillna(0)
tripChain3['하차역ID1'] = tripChain3['하차역ID1'].fillna(0)
tripChain3['하차역ID2'] = tripChain3['하차역ID2'].fillna(0)
tripChain3['하차역ID3'] = tripChain3['하차역ID3'].fillna(0)
tripChain3['하차역ID4'] = tripChain3['하차역ID4'].fillna(0)

bus_station_user_num = {}

for index, row in tripChain3.iterrows():
    if row['승차역ID1'] in bus_station_user_num:
        bus_station_user_num[row['승차역ID1']] = bus_station_user_num[row['승차역ID1']] + 1
    else:
        bus_station_user_num[row['승차역ID1']] = 1
        
    if row['하차역ID1'] == row['승차역ID2']:
        if row['하차역ID1'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID1']] = bus_station_user_num[row['하차역ID1']] + 1
        else:
            bus_station_user_num[row['하차역ID1']] = 1
    else:
        if row['하차역ID1'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID1']] = bus_station_user_num[row['하차역ID1']] + 1
        else:
            bus_station_user_num[row['하차역ID1']] = 1
        if row['승차역ID2'] in bus_station_user_num:
            bus_station_user_num[row['승차역ID2']] = bus_station_user_num[row['승차역ID2']] + 1
        else:
            bus_station_user_num[row['승차역ID2']] = 1
            
            
    if row['하차역ID2'] == row['승차역ID3']:
        if row['하차역ID2'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID2']] = bus_station_user_num[row['하차역ID2']] + 1
        else:
            bus_station_user_num[row['하차역ID2']] = 1
    else:
        if row['하차역ID2'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID2']] = bus_station_user_num[row['하차역ID2']] + 1
        else:
            bus_station_user_num[row['하차역ID2']] = 1
        if row['승차역ID3'] in bus_station_user_num:
            bus_station_user_num[row['승차역ID3']] = bus_station_user_num[row['승차역ID3']] + 1
        else:
            bus_station_user_num[row['승차역ID3']] = 1
            
    if row['하차역ID3'] == row['승차역ID4']:
        if row['하차역ID3'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID3']] = bus_station_user_num[row['하차역ID3']] + 1
        else:
            bus_station_user_num[row['하차역ID3']] = 1
    else:
        if row['하차역ID3'] in bus_station_user_num:
            bus_station_user_num[row['하차역ID3']] = bus_station_user_num[row['하차역ID3']] + 1
        else:
            bus_station_user_num[row['하차역ID3']] = 1
        if row['승차역ID4'] in bus_station_user_num:
            bus_station_user_num[row['승차역ID4']] = bus_station_user_num[row['승차역ID4']] + 1
        else:
            bus_station_user_num[row['승차역ID4']] = 1
            
    if row['하차역ID4'] in bus_station_user_num:
        bus_station_user_num[row['하차역ID4']] = bus_station_user_num[row['하차역ID4']] + 1
    else:
        bus_station_user_num[row['하차역ID4']] = 1
    
most_station = pd.DataFrame.from_dict(bus_station_user_num, orient='index')
most_station.columns = ['이용횟수']
most_station = most_station.drop(0.0)
most_station

most_station.to_csv('station_usage_count.csv', sep=',')

In [ ]:
most_stations = pd.read_csv('./station_usage_count.csv')
most_stations = most_stations.rename(columns={'Unnamed: 0' : 'pr_station_id' })
most_stations.sort_values(by = '이용횟수', ascending=False)

In [ ]:
stations2

In [ ]:
most_stations2 = pd.merge(most_stations, stations2[['시군명', '정류소명', 'WGS84위도', 'WGS84경도', '이비카드정류장ID']], how='left', left_on='pr_station_id', right_on = '이비카드정류장ID')
most_stations2 = most_stations2.drop(['이비카드정류장ID'], axis=1)
most_stations2.drop_duplicates(subset ="pr_station_id", keep = 'first', inplace = True) 
most_stations2

In [ ]:
top_hwaseong_stations = most_stations2[most_stations2['시군명'] == '화성시'].sort_values(by='이용횟수', ascending=False).head(60)
top_hwaseong_stations

In [ ]:
RouteStationInfo_latlon[RouteStationInfo_latlon['WGS84위도'].isna()]

In [ ]:
RouteStationInfo_latlon.set_value(2238014, 'WGS84위도', 37.190923) 
RouteStationInfo_latlon.set_value(2238014, 'WGS84경도', 127.09686) 

RouteStationInfo_latlon.set_value(2238018, 'WGS84위도', 37.190191) 
RouteStationInfo_latlon.set_value(2238018, 'WGS84경도', 127.0680229) 


RouteStationInfo_latlon.set_value(2238020, 'WGS84위도', 37.202142) 
RouteStationInfo_latlon.set_value(2238020, 'WGS84경도', 127.03504) 


RouteStationInfo_latlon.set_value(2238023, 'WGS84위도', 37.190191) 
RouteStationInfo_latlon.set_value(2238023, 'WGS84경도', 127.0680229) 

RouteStationInfo_latlon.set_value(2238027, 'WGS84위도', 37.190923) 
RouteStationInfo_latlon.set_value(2238027, 'WGS84경도', 127.09686) 

RouteStationInfo_latlon.set_value(2248696, 'WGS84위도', 37.127837) 
RouteStationInfo_latlon.set_value(2248696, 'WGS84경도', 126.930882) 

RouteStationInfo_latlon.set_value(2249476, 'WGS84위도', 37.127837) 
RouteStationInfo_latlon.set_value(2249476, 'WGS84경도', 126.930882) 

RouteStationInfo_latlon.set_value(2250956, 'WGS84위도', 37.208539) 
RouteStationInfo_latlon.set_value(2250956, 'WGS84경도',126.857352) 

RouteStationInfo_latlon.set_value(2256439, 'WGS84위도', 37.11963) 
RouteStationInfo_latlon.set_value(2256439, 'WGS84경도', 126.911271) 

RouteStationInfo_latlon.set_value(2262795, 'WGS84위도', 37.195981) 
RouteStationInfo_latlon.set_value(2262795, 'WGS84경도',127.073788) 

##
RouteStationInfo_latlon.set_value(2263501, 'WGS84위도', 37.212158) 
RouteStationInfo_latlon.set_value(2263501, 'WGS84경도',127.109429) 

RouteStationInfo_latlon.set_value(2263516, 'WGS84위도', 37.2121528) 
RouteStationInfo_latlon.set_value(2263516, 'WGS84경도',127.076507 ) 

RouteStationInfo_latlon.set_value(2263522, 'WGS84위도', 37.164711) 
RouteStationInfo_latlon.set_value(2263522, 'WGS84경도', 127.093478) 

RouteStationInfo_latlon.set_value(2263523, 'WGS84위도', 37.165087) 
RouteStationInfo_latlon.set_value(2263523, 'WGS84경도', 127.099104) 

RouteStationInfo_latlon.set_value(2602943, 'WGS84위도', 37.172513) 
RouteStationInfo_latlon.set_value(2602943, 'WGS84경도', 126.767237) 

RouteStationInfo_latlon.set_value(2610265, 'WGS84위도', 37.2667640) 
RouteStationInfo_latlon.set_value(2610265, 'WGS84경도', 126.8098909) 

RouteStationInfo_latlon.set_value(2610267, 'WGS84위도', 37.252098) 
RouteStationInfo_latlon.set_value(2610267, 'WGS84경도',126.813888 ) 

RouteStationInfo_latlon.set_value(2610269, 'WGS84위도', 37.252098) 
RouteStationInfo_latlon.set_value(2610269, 'WGS84경도', 126.813888) 

RouteStationInfo_latlon.set_value(2610271, 'WGS84위도', 37.2667640) 
RouteStationInfo_latlon.set_value(2610271, 'WGS84경도', 126.8098909) 

RouteStationInfo_latlon.set_value(2610343, 'WGS84위도', 37.200464) 
RouteStationInfo_latlon.set_value(2610343, 'WGS84경도', 126.821292)

RouteStationInfo_latlon.set_value(2610344, 'WGS84위도', 37.2341376) 
RouteStationInfo_latlon.set_value(2610344, 'WGS84경도', 126.8203485)

RouteStationInfo_latlon.set_value(2610345, 'WGS84위도', 37.2341376) 
RouteStationInfo_latlon.set_value(2610345, 'WGS84경도', 126.8203485)

RouteStationInfo_latlon.set_value(2621065, 'WGS84위도', 37.1513829) 
RouteStationInfo_latlon.set_value(2621065, 'WGS84경도',126.9284357 )

RouteStationInfo_latlon.set_value(2621066, 'WGS84위도', 37.1513829) 
RouteStationInfo_latlon.set_value(2621066, 'WGS84경도',126.9284357 )

##

RouteStationInfo_latlon.set_value(2250957, 'WGS84위도', 37.200277) 
RouteStationInfo_latlon.set_value(2250957, 'WGS84경도',126.866849 )


RouteStationInfo_latlon.set_value(2251383, 'WGS84위도', 37.200277) 
RouteStationInfo_latlon.set_value(2251383, 'WGS84경도',126.866849 )

RouteStationInfo_latlon.set_value(2251384, 'WGS84위도', 37.208539) 
RouteStationInfo_latlon.set_value(2251384, 'WGS84경도',126.857352)

In [ ]:
import folium

map_osm = folium.Map(location=[37.153952,126.9116727], zoom_start=11)

for index, row in top_hwaseong_stations.iterrows():
    folium.Marker([row['WGS84위도'], row['WGS84경도']], popup=row['정류소명'], icon = folium.Icon(icon='cloud')).add_to(map_osm)

All_busline = []
bus_num_ = 0
for j in range(len(hwaseong_buses)):
    tmp_busline = RouteStationInfo_latlon[RouteStationInfo_latlon['pr_station_id'] == hwaseong_buses[j]].sort_values(by='bus_line_no_seq')
    tmp_buslineArr = []
    for i in range(len(tmp_busline)):
        tmp = tmp_busline.iloc[i]
        tmp_buslineArr.append((tmp['WGS84위도'], tmp['WGS84경도']))
    All_busline.append(tmp_buslineArr)
    bus_num_ += 1

for i in range(len(All_busline)):
    if(len(All_busline[i]) == 0):
        continue
    folium.PolyLine(All_busline[i],
                    popup = pd.DataFrame(RouteStationInfo_latlon[(RouteStationInfo_latlon['WGS84위도'] == All_busline[9][1][0]) & (RouteStationInfo_latlon['WGS84경도'] == All_busline[9][1][1])]['bus_line_no']).iloc[0].iloc[0],
                    color="blue", weight=2.5, opacity=1).add_to(map_osm)

map_osm.save('top_bus_stations.html')
map_osm

In [ ]:
import folium

map_osm2 = folium.Map(location=[37.213952,126.9626727], zoom_start=12)

for index, row in top_hwaseong_stations.iterrows():
    folium.Marker([row['WGS84위도'], row['WGS84경도']], popup=row['정류소명'], icon = folium.Icon(icon='cloud')).add_to(map_osm2)
   
map_osm2.save('top_bus_stations_without_route.html')
map_osm2

In [ ]:
## 이용날짜별 정류장 이용수
tripChain3['이용날짜'] = tripChain3.최초승차일시.astype(str)
tripChain3['이용날짜'] = tripChain3.이용날짜.str.slice(0, 8)
tripChain3['이용날짜'].unique()

In [ ]:
def usage_calculate(table, usage_table):
    for index, row in table.iterrows():
        if row['승차역ID1'] in usage_table:
            usage_table[row['승차역ID1']] = usage_table[row['승차역ID1']] + 1
        else:
            usage_table[row['승차역ID1']] = 1

        if row['하차역ID1'] == row['승차역ID2']:
            if row['하차역ID1'] in usage_table:
                usage_table[row['하차역ID1']] = usage_table[row['하차역ID1']] + 1
            else:
                usage_table[row['하차역ID1']] = 1
        else:
            if row['하차역ID1'] in usage_table:
                usage_table[row['하차역ID1']] = usage_table[row['하차역ID1']] + 1
            else:
                usage_table[row['하차역ID1']] = 1
            if row['승차역ID2'] in usage_table:
                usage_table[row['승차역ID2']] = usage_table[row['승차역ID2']] + 1
            else:
                usage_table[row['승차역ID2']] = 1


        if row['하차역ID2'] == row['승차역ID3']:
            if row['하차역ID2'] in usage_table:
                usage_table[row['하차역ID2']] = usage_table[row['하차역ID2']] + 1
            else:
                usage_table[row['하차역ID2']] = 1
        else:
            if row['하차역ID2'] in usage_table:
                usage_table[row['하차역ID2']] = usage_table[row['하차역ID2']] + 1
            else:
                usage_table[row['하차역ID2']] = 1
            if row['승차역ID3'] in usage_table:
                usage_table[row['승차역ID3']] = usage_table[row['승차역ID3']] + 1
            else:
                usage_table[row['승차역ID3']] = 1

        if row['하차역ID3'] == row['승차역ID4']:
            if row['하차역ID3'] in usage_table:
                usage_table[row['하차역ID3']] = usage_table[row['하차역ID3']] + 1
            else:
                usage_table[row['하차역ID3']] = 1
        else:
            if row['하차역ID3'] in usage_table:
                usage_table[row['하차역ID3']] = usage_table[row['하차역ID3']] + 1
            else:
                usage_table[row['하차역ID3']] = 1
            if row['승차역ID4'] in usage_table:
                usage_table[row['승차역ID4']] = usage_table[row['승차역ID4']] + 1
            else:
                usage_table[row['승차역ID4']] = 1

        if row['하차역ID4'] in usage_table:
            usage_table[row['하차역ID4']] = usage_table[row['하차역ID4']] + 1
        else:
            usage_table[row['하차역ID4']] = 1
            
    return usage_table

usage_20180701 = pd.DataFrame(tripChain3[tripChain3['이용날짜'] == '20180701'])
usage_count_20180701 = {}
usage_count_20180701 = usage_calculate(usage_20180701, usage_count_20180701)
usage_count_20180701 = pd.DataFrame.from_dict(usage_count_20180701, orient='index')
usage_count_20180701.columns = ['20180701이용횟수']
usage_count_20180701 = usage_count_20180701.drop(0.0)
usage_count_20180701.to_csv('usage_count_20180701.csv', sep=',')



usage_20180702 = pd.DataFrame(tripChain3[tripChain3['이용날짜'] == '20180702'])
usage_count_20180702 = {}
usage_count_20180702 = usage_calculate(usage_20180702, usage_count_20180702)
usage_count_20180702 = pd.DataFrame.from_dict(usage_count_20180702, orient='index')
usage_count_20180702.columns = ['20180702이용횟수']
usage_count_20180702 = usage_count_20180702.drop(0.0)
usage_count_20180702.to_csv('usage_count_20180702.csv', sep=',')




usage_20180703 = pd.DataFrame(tripChain3[tripChain3['이용날짜'] == '20180703'])
usage_count_20180703 = {}
usage_count_20180703 = usage_calculate(usage_20180703, usage_count_20180703)
usage_count_20180703 = pd.DataFrame.from_dict(usage_count_20180703, orient='index')
usage_count_20180703.columns = ['20180703이용횟수']
usage_count_20180703 = usage_count_20180703.drop(0.0)
usage_count_20180703.to_csv('usage_count_20180703.csv', sep=',')

usage_20180704 = pd.DataFrame(tripChain3[tripChain3['이용날짜'] == '20180704'])
usage_count_20180704 = {}
usage_count_20180704 = usage_calculate(usage_20180704, usage_count_20180704)
usage_count_20180704 = pd.DataFrame.from_dict(usage_count_20180704, orient='index')
usage_count_20180704.columns = ['20180704이용횟수']
usage_count_20180704 = usage_count_20180704.drop(0.0)
usage_count_20180704.to_csv('usage_count_20180704.csv', sep=',')

In [ ]:
usage_count_20180701 = pd.read_csv('./usage_count_20180701.csv')
usage_count_20180701 = usage_count_20180701.rename(columns={'Unnamed: 0' : 'station_id' })
usage_count_20180701.sort_values(by = '20180701이용횟수', ascending=False)

In [ ]:
usage_count_20180702 = pd.read_csv('./usage_count_20180702.csv')
usage_count_20180702 = usage_count_20180702.rename(columns={'Unnamed: 0' : 'station_id' })
usage_count_20180702.sort_values(by = '20180702이용횟수', ascending=False)

In [ ]:
usage_count_20180703 = pd.read_csv('./usage_count_20180703.csv')
usage_count_20180703 = usage_count_20180703.rename(columns={'Unnamed: 0' : 'station_id' })
usage_count_20180703.sort_values(by = '20180703이용횟수', ascending=False)

In [ ]:
usage_count_20180704 = pd.read_csv('./usage_count_20180704.csv')
usage_count_20180704 = usage_count_20180704.rename(columns={'Unnamed: 0' : 'station_id' })
usage_count_20180704.sort_values(by = '20180704이용횟수', ascending=False)

In [ ]:
usage_by_date = usage_count_20180701.merge(usage_count_20180702,on='station_id').merge(usage_count_20180703,on='station_id').merge(usage_count_20180704, on='station_id')
usage_by_date

In [ ]:
usage_by_date = pd.merge(usage_by_date, stations2[['시군명', '정류소명', 'WGS84위도', 'WGS84경도', '이비카드정류장ID']], how='left', left_on='station_id', right_on = '이비카드정류장ID')
usage_by_date = usage_by_date.drop(['이비카드정류장ID'], axis=1)
usage_by_date.drop_duplicates(subset ="station_id", keep = 'first', inplace = True) 
usage_by_date

In [ ]:
top_hwaseong_stations_20180701 = usage_by_date[usage_by_date['시군명'] == '화성시'].sort_values(by='20180701이용횟수', ascending=False).head(60)
top_hwaseong_stations_20180701

In [ ]:
top_hwaseong_stations_20180702 = usage_by_date[usage_by_date['시군명'] == '화성시'].sort_values(by='20180702이용횟수', ascending=False).head(60)
top_hwaseong_stations_20180702

In [ ]:
top_hwaseong_stations_20180703 = usage_by_date[usage_by_date['시군명'] == '화성시'].sort_values(by='20180703이용횟수', ascending=False).head(60)
top_hwaseong_stations_20180703

In [ ]:
top_hwaseong_stations_20180704 = usage_by_date[usage_by_date['시군명'] == '화성시'].sort_values(by='20180704이용횟수', ascending=False).head(60)
top_hwaseong_stations_20180704

In [ ]:
usage_by_date_on_map = folium.Map(location=[37.193952,126.9626727], zoom_start=11.5)

for index, row in top_hwaseong_stations_20180701.iterrows():
    folium.Marker([row['WGS84위도'] + 0.001, row['WGS84경도'] + 0.001], popup=row['정류소명'], icon = folium.Icon(color='lightblue')).add_to(usage_by_date_on_map)

for index, row in top_hwaseong_stations_20180702.iterrows():
    folium.Marker([row['WGS84위도'], row['WGS84경도']], popup=row['정류소명'], icon = folium.Icon(color='red')).add_to(usage_by_date_on_map)
    
for index, row in top_hwaseong_stations_20180703.iterrows():
    folium.Marker([row['WGS84위도'], row['WGS84경도']], popup=row['정류소명'], icon = folium.Icon(color='red')).add_to(usage_by_date_on_map)
    
for index, row in top_hwaseong_stations_20180704.iterrows():
    folium.Marker([row['WGS84위도'], row['WGS84경도']], popup=row['정류소명'], icon = folium.Icon(color='red')).add_to(usage_by_date_on_map)
    
usage_by_date_on_map.save('top_bus_station_by_date.html')
usage_by_date_on_map